import type { Instrument } from './model';

// Story 9.1: 20 canonical instruments split 4 per family. Each row's
// defaultTemplateId / defaultGuidanceReferenceId matches an entry in the
// work-packages template registry (templateRegistry.ts), so a supervisor-
// authored package is built from the same template payload shape as seed
// packages.
export function buildSeedInstruments(): Instrument[] {
  return [
    // Pressure transmitters (4)
    {
      id: 'inst-pt-201',
      tagCode: 'PT-201',
      shortDescription: 'Reactor inlet pressure transmitter',
      area: 'South Unit',
      parentAssetReference: 'asset-reactor-inlet-01',
      instrumentFamily: 'pressure transmitter',
      instrumentSubtype: 'smart transmitter',
      measuredVariable: 'pressure',
      signalType: '4-20mA',
      range: { min: 0, max: 16, unit: 'bar' },
      tolerance: '+/-0.25% span',
      criticality: 'high',
      defaultTemplateId: 'tpl-pressure-as-found',
      defaultGuidanceReferenceId: 'guide-pressure-loop-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-pt-202',
      tagCode: 'PT-202',
      shortDescription: 'Compressor discharge pressure',
      area: 'South Unit',
      parentAssetReference: 'asset-compressor-discharge-01',
      instrumentFamily: 'pressure transmitter',
      instrumentSubtype: 'smart transmitter',
      measuredVariable: 'pressure',
      signalType: '4-20mA',
      range: { min: 0, max: 40, unit: 'bar' },
      tolerance: '+/-0.25% span',
      criticality: 'high',
      defaultTemplateId: 'tpl-pressure-as-found',
      defaultGuidanceReferenceId: 'guide-pressure-loop-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-pt-203',
      tagCode: 'PT-203',
      shortDescription: 'Utility steam header pressure',
      area: 'Utilities',
      parentAssetReference: 'asset-steam-header-01',
      instrumentFamily: 'pressure transmitter',
      instrumentSubtype: 'gauge pressure transmitter',
      measuredVariable: 'pressure',
      signalType: '4-20mA',
      range: { min: 0, max: 25, unit: 'bar' },
      tolerance: '+/-0.5% span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-pressure-as-found',
      defaultGuidanceReferenceId: 'guide-pressure-loop-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-pt-204',
      tagCode: 'PT-204',
      shortDescription: 'Cooling tower return pressure',
      area: 'Utilities',
      parentAssetReference: 'asset-cooling-return-01',
      instrumentFamily: 'pressure transmitter',
      instrumentSubtype: 'gauge pressure transmitter',
      measuredVariable: 'pressure',
      signalType: '4-20mA',
      range: { min: 0, max: 6, unit: 'bar' },
      tolerance: '+/-0.5% span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-pressure-as-found',
      defaultGuidanceReferenceId: 'guide-pressure-loop-check',
      defaultHistorySummaryId: null,
    },

    // Temperature transmitters (4)
    {
      id: 'inst-tt-301',
      tagCode: 'TT-301',
      shortDescription: 'Reactor outlet temperature',
      area: 'South Unit',
      parentAssetReference: 'asset-reactor-outlet-01',
      instrumentFamily: 'temperature transmitter / RTD input',
      instrumentSubtype: 'RTD input',
      measuredVariable: 'temperature',
      signalType: '4-20mA',
      range: { min: 0, max: 400, unit: 'C' },
      tolerance: '+/-0.3C',
      criticality: 'high',
      defaultTemplateId: 'tpl-temperature-calibration-verification',
      defaultGuidanceReferenceId: 'guide-rtd-input-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-tt-302',
      tagCode: 'TT-302',
      shortDescription: 'Storage tank ambient temperature',
      area: 'Tank Farm',
      parentAssetReference: 'tank-302',
      instrumentFamily: 'temperature transmitter / RTD input',
      instrumentSubtype: 'thermocouple input',
      measuredVariable: 'temperature',
      signalType: '4-20mA',
      range: { min: -20, max: 80, unit: 'C' },
      tolerance: '+/-0.5C',
      criticality: 'medium',
      defaultTemplateId: 'tpl-temperature-calibration-verification',
      defaultGuidanceReferenceId: 'guide-rtd-input-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-tt-303',
      tagCode: 'TT-303',
      shortDescription: 'Heat exchanger shell temperature',
      area: 'North Unit',
      parentAssetReference: 'asset-exchanger-shell-03',
      instrumentFamily: 'temperature transmitter / RTD input',
      instrumentSubtype: 'RTD input',
      measuredVariable: 'temperature',
      signalType: '4-20mA',
      range: { min: 0, max: 200, unit: 'C' },
      tolerance: '+/-0.3C',
      criticality: 'medium',
      defaultTemplateId: 'tpl-temperature-calibration-verification',
      defaultGuidanceReferenceId: 'guide-rtd-input-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-tt-304',
      tagCode: 'TT-304',
      shortDescription: 'Boiler feedwater temperature',
      area: 'Utilities',
      parentAssetReference: 'asset-feedwater-04',
      instrumentFamily: 'temperature transmitter / RTD input',
      instrumentSubtype: 'RTD input',
      measuredVariable: 'temperature',
      signalType: '4-20mA',
      range: { min: 0, max: 150, unit: 'C' },
      tolerance: '+/-0.4C',
      criticality: 'high',
      defaultTemplateId: 'tpl-temperature-calibration-verification',
      defaultGuidanceReferenceId: 'guide-rtd-input-check',
      defaultHistorySummaryId: null,
    },

    // Level transmitters (4)
    {
      id: 'inst-lt-501',
      tagCode: 'LT-501',
      shortDescription: 'Buffer tank level transmitter',
      area: 'Tank Farm',
      parentAssetReference: 'tank-501',
      instrumentFamily: 'level transmitter',
      instrumentSubtype: 'guided wave radar',
      measuredVariable: 'level',
      signalType: '4-20mA',
      range: { min: 0, max: 12, unit: 'm' },
      tolerance: '+/-0.2% calibrated span',
      criticality: 'high',
      defaultTemplateId: 'tpl-level-basic-calibration',
      defaultGuidanceReferenceId: 'guide-level-reference-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-lt-502',
      tagCode: 'LT-502',
      shortDescription: 'Reactor vessel level',
      area: 'South Unit',
      parentAssetReference: 'vessel-502',
      instrumentFamily: 'level transmitter',
      instrumentSubtype: 'differential pressure level',
      measuredVariable: 'level',
      signalType: '4-20mA',
      range: { min: 0, max: 5, unit: 'm' },
      tolerance: '+/-0.5% calibrated span',
      criticality: 'high',
      defaultTemplateId: 'tpl-level-basic-calibration',
      defaultGuidanceReferenceId: 'guide-level-reference-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-lt-503',
      tagCode: 'LT-503',
      shortDescription: 'Day-tank level transmitter',
      area: 'Utilities',
      parentAssetReference: 'tank-503',
      instrumentFamily: 'level transmitter',
      instrumentSubtype: 'guided wave radar',
      measuredVariable: 'level',
      signalType: '4-20mA',
      range: { min: 0, max: 4, unit: 'm' },
      tolerance: '+/-0.5% calibrated span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-level-basic-calibration',
      defaultGuidanceReferenceId: 'guide-level-reference-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-lt-504',
      tagCode: 'LT-504',
      shortDescription: 'Condensate receiver level',
      area: 'Utilities',
      parentAssetReference: 'asset-condensate-receiver-04',
      instrumentFamily: 'level transmitter',
      instrumentSubtype: 'differential pressure level',
      measuredVariable: 'level',
      signalType: '4-20mA',
      range: { min: 0, max: 2, unit: 'm' },
      tolerance: '+/-0.5% calibrated span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-level-basic-calibration',
      defaultGuidanceReferenceId: 'guide-level-reference-check',
      defaultHistorySummaryId: null,
    },

    // Control valves with positioners (4)
    {
      id: 'inst-xv-601',
      tagCode: 'XV-601',
      shortDescription: 'Reactor inlet block valve',
      area: 'South Unit',
      parentAssetReference: 'valve-xv-601',
      instrumentFamily: 'control valve with positioner',
      instrumentSubtype: 'on-off with smart positioner',
      measuredVariable: 'position',
      signalType: 'digital-position-feedback',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-2% span',
      criticality: 'high',
      defaultTemplateId: 'tpl-valve-stroke-test',
      defaultGuidanceReferenceId: 'guide-valve-stroke-baseline',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-xv-602',
      tagCode: 'XV-602',
      shortDescription: 'Steam vent isolation valve',
      area: 'Utilities',
      parentAssetReference: 'valve-xv-602',
      instrumentFamily: 'control valve with positioner',
      instrumentSubtype: 'on-off with smart positioner',
      measuredVariable: 'position',
      signalType: 'digital-position-feedback',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-2% span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-valve-stroke-test',
      defaultGuidanceReferenceId: 'guide-valve-stroke-baseline',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-xv-603',
      tagCode: 'XV-603',
      shortDescription: 'Tank farm transfer valve',
      area: 'Tank Farm',
      parentAssetReference: 'valve-xv-603',
      instrumentFamily: 'control valve with positioner',
      instrumentSubtype: 'modulating with smart positioner',
      measuredVariable: 'position',
      signalType: 'digital-position-feedback',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-2% span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-valve-stroke-test',
      defaultGuidanceReferenceId: 'guide-valve-stroke-baseline',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-xv-604',
      tagCode: 'XV-604',
      shortDescription: 'Cooling water bypass valve',
      area: 'Utilities',
      parentAssetReference: 'valve-xv-604',
      instrumentFamily: 'control valve with positioner',
      instrumentSubtype: 'modulating with smart positioner',
      measuredVariable: 'position',
      signalType: 'digital-position-feedback',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-2% span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-valve-stroke-test',
      defaultGuidanceReferenceId: 'guide-valve-stroke-baseline',
      defaultHistorySummaryId: null,
    },

    // Analog 4-20 mA loops (4)
    {
      id: 'inst-ai-701',
      tagCode: 'AI-701',
      shortDescription: 'South process control loop',
      area: 'South Unit',
      parentAssetReference: 'loop-ai-701',
      instrumentFamily: 'analog 4-20 mA loop',
      instrumentSubtype: 'isolated analog input loop',
      measuredVariable: 'process value',
      signalType: '4-20mA',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-1% span',
      criticality: 'high',
      defaultTemplateId: 'tpl-loop-integrity-check',
      defaultGuidanceReferenceId: 'guide-loop-integrity-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-ai-702',
      tagCode: 'AI-702',
      shortDescription: 'Tank farm flow loop',
      area: 'Tank Farm',
      parentAssetReference: 'loop-ai-702',
      instrumentFamily: 'analog 4-20 mA loop',
      instrumentSubtype: 'isolated analog input loop',
      measuredVariable: 'process value',
      signalType: '4-20mA',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-1% span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-loop-integrity-check',
      defaultGuidanceReferenceId: 'guide-loop-integrity-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-ai-703',
      tagCode: 'AI-703',
      shortDescription: 'Utility consumption loop',
      area: 'Utilities',
      parentAssetReference: 'loop-ai-703',
      instrumentFamily: 'analog 4-20 mA loop',
      instrumentSubtype: 'isolated analog input loop',
      measuredVariable: 'process value',
      signalType: '4-20mA',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-1% span',
      criticality: 'medium',
      defaultTemplateId: 'tpl-loop-integrity-check',
      defaultGuidanceReferenceId: 'guide-loop-integrity-check',
      defaultHistorySummaryId: null,
    },
    {
      id: 'inst-ai-704',
      tagCode: 'AI-704',
      shortDescription: 'North heat exchanger loop',
      area: 'North Unit',
      parentAssetReference: 'loop-ai-704',
      instrumentFamily: 'analog 4-20 mA loop',
      instrumentSubtype: 'isolated analog input loop',
      measuredVariable: 'process value',
      signalType: '4-20mA',
      range: { min: 0, max: 100, unit: '%' },
      tolerance: '+/-1% span',
      criticality: 'high',
      defaultTemplateId: 'tpl-loop-integrity-check',
      defaultGuidanceReferenceId: 'guide-loop-integrity-check',
      defaultHistorySummaryId: null,
    },
  ];
}
